services:
  mysql:
    image: 'mysql:8.0'
    environment:
      - 'MYSQL_DATABASE=usuarios'
      - 'MYSQL_PASSWORD=root'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=jose'
    ports:
      - '3306:3306'

