
services:
  microservicio-login-image:
    build:
      context: .
      dockerfile: Dockerfile
    image: microservicio-login-image
    container_name: microservicio-login-container
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
    depends_on:
      - mysql_database
    networks:
      - microservicio-login-network

  mysql_database:
    image: mysql:8.0
    container_name: mysql_database
    environment:
      - MYSQL_ROOT_PASSWORD=jose
      - MYSQL_DATABASE=Login
    ports:
      - "3307:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - microservicio-login-network

volumes:
  mysql-volume:

networks:
  microservicio-login-network:
    name: microservicio-login-network
    driver: bridge
